import type { AppListing, PrivacyData } from '../models/app'

interface AppEntry {
  id: string
  name: string
  icon: string
  listing: Omit<AppListing, 'id' | 'name' | 'icon'>
  privacy: Omit<PrivacyData, 'appName' | 'icon'>
}

const APPS_DATA: AppEntry[] = [
  {
    id: 'sg-weather',
    name: 'SG Weather Application',
    icon: 'https://res.cloudinary.com/duxmjjxns/image/upload/t_portfolio_icon/portfolio/projects/uy8pbwcpu3kwhhtton1d',
    listing: {
      subtitle: 'A more accurate SG weather app',
      description:
        'Reads temperature from approximately 22 Singapore locations sourced from NEA (National Environment Agency) via data.gov.sg. Provides location-specific readings rather than a single generalised value — covering areas like Jurong, Pasir Ris, and more. No advertisements, on-device location calculations to protect your privacy, and home screen widgets included.',
      platforms: ['iOS', 'iPadOS', 'macOS', 'watchOS'],
      price: 'Free',
      storeUrl: 'https://apps.apple.com/sg/app/sg-weather-application/id1535913667',
      category: 'Reference',
    },
    privacy: {
      footerText: 'SG Weather · For Singapore, by Singapore',
      intro: "Your privacy is fundamental to how SG Weather is built. This page explains exactly what happens — and what doesn't happen — with your data.",
      sections: [
        {
          color: '#38bdf8',
          title: 'Device Identifier',
          facts: [
            'No data of you is collected nor processed.',
            'A unique identifier is generated on your device to identify the device. The identifier is generated by Apple and will be used to ensure uniqueness of data.',
          ],
        },
        {
          color: '#f97316',
          title: 'Location Privacy',
          facts: [
            'A rough estimation of the place you are in is calculated on your phone, then used to request only the weather data you need. Your precise location never leaves your device.',
          ],
        },
      ],
    },
  },
]

export const APPS: AppListing[] = APPS_DATA.map((a) => ({
  id: a.id,
  name: a.name,
  icon: a.icon,
  ...a.listing,
}))

export const PRIVACY_DATA: Record<string, PrivacyData> = Object.fromEntries(
  APPS_DATA.map((a) => [a.id, { appName: a.name, icon: a.icon, ...a.privacy }]),
)
