export interface PrivacySection {
  color: string
  title: string
  facts: string[]
}

export interface PrivacyData {
  appName: string
  icon: string
  footerText: string
  intro: string
  sections: PrivacySection[]
}

export const PRIVACY_DATA: Record<string, PrivacyData> = {
  'sg-weather': {
    appName: 'SG Weather',
    icon: 'https://res.cloudinary.com/duxmjjxns/image/upload/t_portfolio_icon/portfolio/projects/uy8pbwcpu3kwhhtton1d',
    footerText: 'SG Weather · For Singapore, by Singapore',
    intro:
      "Your privacy is fundamental to how SG Weather is built. This page explains exactly what happens — and what doesn't happen — with your data.",
    sections: [
      {
        color: '#38bdf8',
        title: 'Device Identifier',
        facts: [
          'No data of you is collected nor processed.',
          'A unique identifier is generated on your device to identify the device. The identifier is generated by Apple and will be used to ensure uniqueness of data.',
        ],
      },
      {
        color: '#f97316',
        title: 'Location Privacy',
        facts: [
          'A rough estimation of the place you are in is calculated on your phone, then used to request only the weather data you need. Your precise location never leaves your device.',
        ],
      },
    ],
  },
}
